print("Hello world plz enter  Raj friends name and birthday")
name1=input("Please enter 1st Friend Name :")
Birthday1=input("Please enter your Date of Birth of 1st friend DD/MM/YY:")
name2=input("Please enter 2nd friend name :") 
Birthday2=input("Please enter your Date of Birth of 2nd friend DD|MM|YY:") 
name3=input("Please enter 3rd friend name :")
Birthday3=input("Please enter your date of birth 3rd friend DD|MM|YY:") 
name4=input("Please enter 4th friend name :")
Birthday4=input("Please enter your date of birth of 4th friend DD|MM|YY:")
name5=input("Please enter 5th friend name :")
Birthday5=input("Please enter your date of birth of 5th friend DD|MM|YY:")
print("Now i will print Arham friends name and date of birth")
print("\n",Birthday1,"\n",name1)
print("\n",Birthday2,"\n",name2)
print("\n",Birthday3,"\n",name3)
print("\n",Birthday4,"\n",name4)
print("\n",Birthday5,"\n",name5)
print("thank you")